### PR TITLE
Pull some fixes from your fork?

### PR DESCRIPTION
**Pull request by falkowich**
Hi,

Is it ok for you that I cherrypick some fixes that you have done?
That would be of great help for me :)

--
Regards Falk

### CODE REVIEW

**Comment by Hardzen** [comment]
Sure, im new to github, what should i do ^^

**Comment by samredinet** [comment]
Oh, I see some stuff in here for nullmailer? 
This mean we might be able to get SMTP alerts up and running in the stable release?

I am currently running Stable, and testing SendMail at the moment within the docker container but its just testing for the time being.

**Comment by sfrod** [comment]
Hey, 

I created a Dockerfile from falkowich/gvm10:psql-latest and added ssmtp to send mails for the alerts and cron to update de database every 2 weeks. And it works fine. 

I'm leaving that here just in case it might interest you. If yes I would take the necessary steps to provide my code.

Best regards,
sfrod

**Comment by sfrod** [comment]
Hey, 
I created a Dockerfile from falkowich/gvm10:psql-latest and added ssmtp to send mails for the alerts and cron to update de database every 2 weeks. And it works fine. 

I'm leaving that here just in case it might interest you. If yes I would take the necessary steps to provide my code.

Best regards,
sfrod

**Pull request closed without merging**
